name: Package and upload to PyPI

# Publish when a (published) GitHub Release is created
on:
  release:
    types:
      - published

jobs:
  build_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install build

      - name: Build
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
